
# See https://developers.cloudflare.com/workers/wrangler/configuration/
name = "waku-project"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat", "nodejs_als" ]
main = "./dist/worker/serve-cloudflare.js"

[assets]
directory = "./dist/assets"
binding = "ASSETS"
html_handling = "drop-trailing-slash" # "single-page-application" | "404-page" | "none"
not_found_handling = "404-page"

[[d1_databases]]
database_name = "retroassembly"
database_id = "e168a68d-c4f4-4cd6-b1d3-667629292674"
preview_database_id = "de33fa50-7be3-4873-8bc0-021758cab19b"
binding = "DB"

[vars]
MAX_ITEMS=10
