export const gbaGames = [
  { fileName: '3weeksinparadise.gba', name: '3 Weeks In Paradise' },
  { fileName: 'agbhack.bin', name: 'AGB_Hack' },
  { fileName: 'agbrogue.bin', name: 'AGB_Rogue' },
  { fileName: 'airball.gba', name: 'Airball GBA' },
  { fileName: 'anguna.gba', name: 'Anguna' },
  { fileName: 'anotherworld.gba', name: 'Another World' },
  { fileName: 'asteroidsb.gba', name: 'Asteroids' },
  { fileName: 'asteroidsp.bin', name: 'Yet Another Asteroids' },
  { fileName: 'astrohawk.bin', name: 'Astrohawk Advance' },
  { fileName: 'awerewolftale.gba', name: 'A WEREWOLF TALE' },
  { fileName: 'balle.gba', name: 'Balle' },
  { fileName: 'battlepicross.gba', name: 'Battle Picross' },
  { fileName: 'blastarenaadvance.gba', name: 'Blast Arena Advance' },
  { fileName: 'blocktrap.gba', name: 'Blocktrap' },
  { fileName: 'bridgeracer.gba', name: 'BridgeRacer' },
  { fileName: 'bunnyxmas.gba', name: 'Bunny Xmas' },
  { fileName: 'bustamove.bin', name: 'Bust A Move' },
  { fileName: 'bytes.gba', name: 'Bytes' },
  { fileName: 'castlemaster.gba', name: 'Castle Master' },
  { fileName: 'cccp.gba', name: 'CCCP' },
  { fileName: 'chaos.bin', name: 'Chaos' },
  { fileName: 'chaosthebattleofwizards.gba', name: 'Chaos - The Battle Of Wizards' },
  { fileName: 'chipadvance.gba', name: 'ChipAdvance' },
  { fileName: 'chocoboworlddeluxe.gba', name: 'Chocobo World Deluxe' },
  { fileName: 'clayshooter.gba', name: 'AGB Clay Pidgeon' },
  { fileName: 'cleangameadvance.gba', name: 'Cleangame Advance' },
  { fileName: 'codenamehacker.gba', name: 'Codename Hacker' },
  { fileName: 'collisioncourse.bin', name: 'Collision Course' },
  { fileName: 'cosmic.gba', name: 'Cosmic Smash Clone' },
  { fileName: 'crystalclearclone.gba', name: 'Crystal Clear Clone' },
  { fileName: 'cyclone.bin', name: 'Cyclone' },
  { fileName: 'cyler.gba', name: 'cyler' },
  { fileName: 'deflektor.gba', name: 'Deflektor' },
  { fileName: 'doomdarksrevenge.gba', name: "Doomdark's Revenge" },
  { fileName: 'elevator.gba', name: 'Elevator' },
  { fileName: 'eliminator.gba', name: 'Eliminator' },
  { fileName: 'factorybots.gba', name: 'Factory Bots' },
  { fileName: 'fredfirefighter.gba', name: 'Fred Firefighter' },
  { fileName: 'frogger.gba', name: 'Frogger' },
  { fileName: 'frogtris.gba', name: 'Frogtris' },
  { fileName: 'gapman.gba', name: 'GapMan' },
  { fileName: 'gbacards.gba', name: 'GBA Card Games' },
  { fileName: 'gbatactics.gba', name: 'GBATACTICS' },
  { fileName: 'goldrunner.gba', name: 'Goldrunner' },
  { fileName: 'goodboyadvance.gba', name: 'GOODBOY ADVANCE' },
  { fileName: 'gorf.gba', name: 'GORF' },
  { fileName: 'hexavirus.gba', name: 'Hexavirus' },
  { fileName: 'hierogyphicman.gba', name: 'Hierogyphic Man' },
  { fileName: 'holyhell.gba', name: 'Holy Hell' },
  { fileName: 'impact.gba', name: 'space impact clone' },
  { fileName: 'jetpack2.gba', name: 'Jetpack 2' },
  { fileName: 'jumpingbarnabe.gba', name: 'Jumping Barnabe' },
  { fileName: 'jumpingjim.gba', name: 'JUMPING JIM' },
  { fileName: 'klanwars.gba', name: 'Klan Wars' },
  { fileName: 'laserchess.bin', name: 'LaserChess' },
  { fileName: 'llamaboost.gba', name: 'Llamaboost' },
  { fileName: 'looped.gba', name: 'looped' },
  { fileName: 'looptheloop.gba', name: 'Loop the Loop' },
  { fileName: 'matrixrunner.gba', name: 'Matrix Runner' },
  { fileName: 'memorymuncha.gba', name: 'Memory Muncha' },
  { fileName: 'metalwarrior4.gba', name: 'Metal Warrior 4: Agents of Metal' },
  { fileName: 'monochromancy.bin', name: 'Monochromancy' },
  { fileName: 'moshpit.gba', name: 'Moshpit' },
  { fileName: 'nebulus.gba', name: 'Nebulus' },
  { fileName: 'negativespace.gba', name: 'Negative Space' },
  { fileName: 'ninjasack.gba', name: 'Ninjasack!' },
  { fileName: 'pacrun.gba', name: 'Pac Run' },
  { fileName: 'paperscissorrocks.gba', name: 'Paper, Scissor, Rocks' },
  { fileName: 'pnakys.bin', name: 'Pnakys' },
  { fileName: 'pocketmeat.gba', name: 'Pocket Meat' },
  { fileName: 'powerpig.gba', name: 'POWERPIG' },
  { fileName: 'pushit.gba', name: 'PUSH-IT' },
  { fileName: 'santassweatshop.gba', name: "Santa's Sweatshop" },
  { fileName: 'shapes.gba', name: 'Shapes' },
  { fileName: 'snakeinthegrass.gba', name: 'Snake in The Grass' },
  { fileName: 'spout.gba', name: 'SPOUT' },
  { fileName: 'superhappy.gba', name: 'SUPER HAPPY BUNNY EX [X-MAS EDITION]' },
  { fileName: 'superwings.gba', name: 'Super Wings' },
  { fileName: 'sworld3.gba', name: 'S World 3' },
  { fileName: 'tailgunner.gba', name: 'TailGunner' },
  { fileName: 'tetravex.gba', name: 'Tetravex' },
  { fileName: 'tetrigram.gba', name: 'Tetrigram' },
  { fileName: 'thelordsofmidnight.gba', name: 'The Lords Of Midnight' },
  { fileName: 'timewalker.gba', name: 'Time Walker' },
  { fileName: 'tronlordgraga.gba', name: 'Tron' },
  { fileName: 'waimanu.gba', name: 'WAIMANU - GRINDING BLOCK ADVENTURE' },
  { fileName: 'wonkieguy.gba', name: 'Wonkie Guy' },
  { fileName: 'yahtzeeherg.gba', name: "Herg's Yahtzee" },
]
