export const nesGames = [
  { fileName: '31in1realgame-multicart.nes', name: '31 In 1 Real Game!' },
  { fileName: '3in12ppak.nes', name: '3-In-1 2P Pak' },
  { fileName: 'ambushed.nes', name: 'Ambushed' },
  { fileName: 'assimilate.nes', name: 'Assimilate' },
  { fileName: 'babelblox.nes', name: 'Babel Blox' },
  { fileName: 'blackboxchallenge.nes', name: 'Black Box Challenge' },
  { fileName: 'blaster.nes', name: 'Big City Sliding Blaster' },
  { fileName: 'bombarray.nes', name: 'Bomb Array' },
  { fileName: 'bootee.nes', name: 'Bootèe' },
  { fileName: 'bronyblaster.nes', name: 'Brony Blaster' },
  { fileName: 'cheril-the-goddess.nes', name: 'Cheril The Goddess' },
  { fileName: 'cl1k.nes', name: 'Cl1k' },
  { fileName: 'croom.nes', name: 'Concentration Room' },
  { fileName: 'dabg.nes', name: 'Debris Dodger' },
  { fileName: 'debrisdodger.nes', name: 'Double Action Blaster Guys' },
  { fileName: 'driar.nes', name: 'Driar' },
  { fileName: 'falling.nes', name: 'Falling' },
  { fileName: 'fff.nes', name: 'F-FF' },
  { fileName: 'filthykitchen.nes', name: 'Filthy Kitchen' },
  { fileName: 'flappybird.nes', name: 'Flappy Bird' },
  { fileName: 'flappyblock.nes', name: 'Flappy Block' },
  { fileName: 'flappyjack.nes', name: 'Flappy Jack' },
  { fileName: 'forpoints.nes', name: 'For Points' },
  { fileName: 'gsm.nes', name: 'GSM' },
  { fileName: 'indivisibleonnes.nes', name: 'Indivisible On NES' },
  { fileName: 'invaders.nes', name: 'Invaders Must Die' },
  { fileName: 'jetpaco.nes', name: 'Jet Paco - Space Agent!' },
  { fileName: 'kyff.nes', name: 'K.Y.F.F.' },
  { fileName: 'lala.nes', name: 'Lala The Magical' },
  { fileName: 'lightshields.nes', name: 'Lightshields' },
  { fileName: 'lunarlimit.nes', name: 'Lunar Limit' },
  { fileName: 'madwizard.nes', name: 'Mad Wizard' },
  { fileName: 'mashymashy.nes', name: 'Mashymashy' },
  { fileName: 'megamountain.nes', name: 'Mega Mountain' },
  { fileName: 'memory.nes', name: 'Memory' },
  { fileName: 'mguard.nes', name: 'Meteor Guard' },
  { fileName: 'mguard2.nes', name: 'Meteor Guard 2' },
  { fileName: 'midnightjogger.nes', name: 'Midnight Jogger' },
  { fileName: 'miedow.nes', name: "Miedow (Cheril's Nightmares)" },
  { fileName: 'mineshaft.nes', name: 'Mineshaft' },
  { fileName: 'mouser2.nes', name: 'Mouser II' },
  { fileName: 'nesertbus.nes', name: 'Nesertbus' },
  { fileName: 'ninjamuncher.nes', name: 'Ninja Muncher' },
  { fileName: 'nintencattheparody.nes', name: 'Nintencat: The Parody' },
  { fileName: 'nomolos.nes', name: 'No Points' },
  { fileName: 'nopoints.nes', name: 'Nomolos: Storming The Catsle' },
  { fileName: 'novathesquirrel.nes', name: 'Nova The Squirrel' },
  { fileName: 'obstacletrek.nes', name: 'Obstacle Trek' },
  { fileName: 'owlia.nes', name: 'Pegs' },
  { fileName: 'pegs.nes', name: 'Pong 1K' },
  { fileName: 'pong1k.nes', name: 'Pong 1K 2P' },
  { fileName: 'pong1k2p.nes', name: 'Ralph 4' },
  { fileName: 'ralph4.nes', name: 'RHDE: Furniture Fight' },
  { fileName: 'rhde.nes', name: 'Rise Of Amondus' },
  { fileName: 'riseofamondus.nes', name: 'Robo-Ninja Climb' },
  { fileName: 'roboninjaclimb.nes', name: 'RobotFindsKitten' },
  { fileName: 'robotfindskitten.nes', name: 'Rock Paper Scissors Lizard Sbock' },
  { fileName: 'roulette.nes', name: 'Russian Roulette [Damian]' },
  { fileName: 'rpsls.nes', name: 'Sgt. Helmet - Training Day' },
  { fileName: 'sgthelmet.nes', name: 'Simone Says' },
  { fileName: 'simonesays.nes', name: 'Sir Adabol Remastered' },
  { fileName: 'sir-ababol-remastered.nes', name: 'Snail Maze' },
  { fileName: 'snailmaze.nes', name: 'Spacey Mcracey' },
  { fileName: 'spaceymcracey.nes', name: 'Star Evil' },
  { fileName: 'starevil.nes', name: 'Super Pakpak' },
  { fileName: 'super-tilt-bro.nes', name: 'Super Tilt Bro.' },
  { fileName: 'superpakpak.nes', name: 'Super Uwol' },
  { fileName: 'superuwol.nes', name: "That's Whack!" },
  { fileName: 'thatswhack.nes', name: 'The Invasion' },
  { fileName: 'theinvasion.nes', name: 'The Legends Of Owlia' },
  { fileName: 'themadwizard.nes', name: 'The Mad Wizard: A Candelabra Chronicle' },
  { fileName: 'theonewiththewalls.nes', name: 'The One With The Walls' },
  { fileName: 'thewit.nes', name: 'The Wit.Nes' },
  { fileName: 'thwaite.nes', name: 'Thwaite' },
  { fileName: 'tictactwop.nes', name: 'Tic Tac Two P' },
  { fileName: 'tictacxo.nes', name: 'Tic Tac Xo' },
  { fileName: 'tigerjenny.nes', name: 'Tiger Jenny' },
  { fileName: 'twindragons.nes', name: 'Twin Dragons' },
  { fileName: 'vigilanteninja.nes', name: 'Vigilante Ninja' },
  { fileName: 'viruscleaner.nes', name: 'Virus Cleaner' },
  { fileName: 'wo-xiang-niao-niao.nes', name: 'Wo Xiang Niao Niao' },
  { fileName: 'yun.nes', name: 'Yun' },
]
