export const atari2600Games = [
  { fileName: 'anguna.bin', name: 'Anguna by Nathan Tolbert (Moonsweeper)' },
  { fileName: 'bitquest.bin', name: 'Bit Quest by Brian W. Shea (Metalbabble)' },
  { fileName: 'bitquest2.bin', name: 'Bit Quest II by Brian W. Shea (Metalbabble)' },
  { fileName: 'dkarcade2600.bin', name: 'DK Arcade 2600 by Byte Knight' },
  { fileName: 'emr.bin', name: 'Evil Magician Returns by Byte Knight' },
  { fileName: 'emrii.bin', name: 'Evil Magician Returns II by Byte Knight' },
  { fileName: 'fishy.bin', name: 'Fishy by Brian W. Shea (Metalbabble)' },
  { fileName: 'flappy_the_duck.bin', name: 'Flappy The Duck by Brian W. Shea (Metalbabble)' },
  { fileName: 'halo2600.bin', name: 'Halo 2600 by Ed Fries' },
  { fileName: 'hauntedbakery.bin', name: 'Haunted Bakery by Denebola Interactive (Phano)' },
  { fileName: 'jammed.bin', name: 'Jammed by Thomas Jentzsch' },
  { fileName: 'kellykangaroo.bin', name: 'Kelly Kangaroo by Denebola Interactive (Phano)' },
  { fileName: 'nanowing.bin', name: 'NanoWing by Brian W. Shea (Metalbabble)' },
  { fileName: 'neko_2600.bin', name: 'Neko 2600 by Brian W. Shea (Metalbabble)' },
  { fileName: 'pothole.bin', name: 'PotHole by Brian W. Shea (Metalbabble)' },
  { fileName: 'roboninjaclimb.bin', name: 'Robo-Ninja Climb by Nathan Tolbert (Moonsweeper)' },
  { fileName: 'runtysrevenge.bin', name: "Runty's Revenge by Guillermo Gee (Squidsee)" },
  { fileName: 'sandcastles.bin', name: 'Sand Castles by Brian W. Shea (Metalbabble)' },
  { fileName: 'solarplexus.bin', name: 'Solar Plexus by Jess Ragan' },
  { fileName: 'stardust.bin', name: 'Stardust by Brian W. Shea (Metalbabble)' },
  { fileName: 'threes.bin', name: 'Three.s by Thomas Jentzsch' },
  { fileName: 'thrust.bin', name: 'Thrust by Thomas Jentzsch' },
  { fileName: 'turtlebay.bin', name: 'Turtle Bay by Unlink2' },
  { fileName: 'winterfortress.bin', name: 'Winter Fortress by Denebola Interactive (Phano)' },
]
