export const mdGames = [
  { fileName: '30yearsofnintendont.bin', name: '30 Years Of Nintendont' },
  { fileName: 'asciiwar.bin', name: 'ASCII WAR' },
  { fileName: 'astroperdido.bin', name: 'Astronauta Perdido (Lost Astronaut)' },
  { fileName: 'barbarian.bin', name: 'Barbarian (CPC)' },
  { fileName: 'bareknuckleprincesss.bin', name: 'Bare Knuckled Princess' },
  { fileName: 'bombonbasiccity.bin', name: 'Bomb on Basic City' },
  { fileName: 'bombx.bin', name: 'BombX' },
  { fileName: 'bottled.md', name: 'BoTTleD - Tower Defense' },
  { fileName: 'breakanegg.bin', name: 'Break An Egg' },
  { fileName: 'cavestory.bin', name: 'Cave Story' },
  { fileName: 'crazycars.bin', name: 'Crazy Cars' },
  { fileName: 'crazydriver.bin', name: 'Crazy Driver' },
  { fileName: 'downforce.bin', name: 'Downforce : Red Hot Princess Carnage' },
  { fileName: 'dragonscastle.bin', name: "Dragon's Castle" },
  { fileName: 'errorrush.bin', name: 'Error Rush' },
  { fileName: 'fixitfelixjr.bin', name: 'Fix It Felix Jr.' },
  { fileName: 'genpoker.bin', name: 'Gen Poker' },
  { fileName: 'glassbreakermd.bin', name: 'Glass Breaker' },
  { fileName: 'goldrush.bin', name: 'Gold Rush' },
  { fileName: 'goplanes.bin', name: 'Goplanes' },
  { fileName: 'gravitypig.bin', name: 'Gravity Pig' },
  { fileName: 'grielsquest.bin', name: 'Griels Quest for the Holy Porron' },
  { fileName: 'headship.bin', name: 'Headship with Lasers' },
  { fileName: 'ikplusdeluxe.bin', name: 'IK+ Deluxe version' },
  { fileName: 'junkbots.bin', name: 'Junkbots' },
  { fileName: 'leomurconspiracy.bin', name: "Leovigildo's Murcian Conspiracy" },
  { fileName: 'mega-cheril-perils.bin', name: 'Mega Cheril Perils' },
  { fileName: 'megaflappysis.bin', name: 'Mega Flappy Sis' },
  { fileName: 'megamindtris.bin', name: 'Mega Squad Advantage' },
  { fileName: 'miniplanets.bin', name: 'Megamindtris' },
  { fileName: 'msa.bin', name: 'Miniplanets' },
  { fileName: 'odeiocarros.bin', name: 'Odeio Carros (I hate cars)' },
  { fileName: 'ohmummy.bin', name: 'Oh Mummy!' },
  { fileName: 'oldtowers.bin', name: 'Old Towers' },
  { fileName: 'papicommandoremix.bin', name: 'Papi Commando (Remix)' },
  { fileName: 'papicommandotennis.bin', name: 'Papi Commando Tennis' },
  { fileName: 'pingouinbleu.bin', name: 'Pingouin Bleu' },
  { fileName: 'pingouinrose.bin', name: 'Pingouin Rose' },
  { fileName: 'plataforma-ultimate.bin', name: 'Plataforma Ultimate' },
  { fileName: 'pongram.bin', name: 'Pong RAM' },
  { fileName: 'projectmd.bin', name: 'Project MD' },
  { fileName: 'racer.bin', name: 'Racer' },
  { fileName: 'radrhino.bin', name: 'Rad Rhino' },
  { fileName: 'redqueenrampage.bin', name: 'Red Queen Rampage' },
  { fileName: 'returntogenesis.bin', name: 'Return To Genesis' },
  { fileName: 'rickdangerous.bin', name: 'Rick Dangerous' },
  { fileName: 'rickdangerous2.bin', name: 'Rick Dangerous II' },
  { fileName: 'scorpionilluminati.bin', name: 'Scorpion Illuminati' },
  { fileName: 'shatteringjaws.md', name: 'Shattering Jaws' },
  { fileName: 'starchaser.bin', name: 'Star Chaser' },
  { fileName: 'tgunii.smd', name: 'T-Gun II' },
  { fileName: 'tronow.bin', name: 'Tro-Now' },
  { fileName: 'twocyclops-fight.bin', name: 'Two Cyclops (Dois Ciclopes)' },
  { fileName: 'twocyclops.bin', name: 'Two Cyclops - Fight Game' },
  { fileName: 'ultimatetetris.bin', name: 'Ultimate Tetris' },
  { fileName: 'vilq.bin', name: 'VilQ' },
  { fileName: 'vilqadventure.bin', name: 'VilQ Adventure' },
  { fileName: 'violencepingouin.bin', name: 'Violence Pingouin' },
  { fileName: 'virtuaworm.bin', name: 'Virtua Worm' },
  { fileName: 'virtuaworm2.bin', name: 'Virtua Worm 2' },
  { fileName: 'wackywilly.bin', name: 'Wacky Willy Weiner Sausage Surfer' },
  { fileName: 'xump2.bin', name: 'Xump 2: Back in Space' },
]
