export const snesGames = [
  { fileName: 'astrohawk.smc', name: 'Astrohawk' },
  { fileName: 'blt.sfc', name: 'Blt' },
  { fileName: 'bucket.smc', name: 'Bucket' },
  { fileName: 'furryrpg.sfc', name: 'Furry RPG' },
  { fileName: 'hilda.sfc', name: 'Hilda' },
  { fileName: 'horizontal-shooter.sfc', name: 'Horizontal Shooter' },
  { fileName: 'jetpilotrising.sfc', name: 'Jet Pilot Rising' },
  { fileName: 'megafamilybros.smc', name: 'Mega Family Bros' },
  { fileName: 'nwarpdaisakusen.smc', name: 'N-Warp Daisakusen' },
  { fileName: 'questformoney.sfc', name: 'Uwol, Quest For Money' },
  { fileName: 'rockfall.smc', name: 'Rockfall' },
  { fileName: 'saf.smc', name: 'Skipp And Friends: Unexpected Journey' },
  { fileName: 'superbossgaiden.sfc', name: 'Super Boss Gaiden' },
  { fileName: 'tchouv2.smc', name: 'Tchou 2' },
]
