
# See https://developers.cloudflare.com/workers/wrangler/configuration/
name = "waku-project"
compatibility_date = "2025-02-25"
compatibility_flags = [ "nodejs_compat", "nodejs_als" ]
main = "./dist/worker/serve-cloudflare.js"

[assets]
directory = "./dist/assets"
binding = "ASSETS"
html_handling = "drop-trailing-slash" # "single-page-application" | "404-page" | "none"
not_found_handling = "404-page"

[[d1_databases]]
database_name = "retroassembly"
database_id = "de33fa50-7be3-4873-8bc0-021758cab19b"
preview_database_id = "local-test-db"
binding = "DB"
migrations_dir = "src/database/migrations"
