name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      VITE_ONEDRIVE_CLIENT_ID: ${{ vars.VITE_ONEDRIVE_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - uses: actions/cache@v3
        with:
          path: tests/fixtures/roms
          key: tests/fixtures/roms

      - run: pnpm lint
      - run: pnpm playwright install chromium
      - run: pnpm prepare-test
      - run: pnpm t
