name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - uses: actions/cache@v3
        with:
          path: tests/fixtures
          key: tests/fixtures

      - run: pnpm lint
      - run: pnpm playwright install
      - run: pnpm prepare-test
      - run: pnpm t
